---
title: "EDAV_Project"
author: "Aashna Kanuga"
date: "12/2/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(GGally)
library(RColorBrewer)

```

## Early Marriage

```{r, include=FALSE}
Early_Marriage<-read_csv("Early_Marriage.csv")
data1 <- subset(Early_Marriage, Early_Marriage$Region!="All Regions" & !duplicated(Early_Marriage$Country) & Early_Marriage$Value>0.1)
```

```{r fig.height=8, fig.width=10}

ggplot(data1) + 
  geom_point(stat = "identity",aes(x=reorder(Country,Value), y=Value, color=Region)) + 
  coord_flip() +
  ggtitle("Percentage of women married at an early age")

```


## Attitude towards violence

```{r, include=FALSE}
Attitudes_Towards_Violence<-read_csv("Attitudes_Towards_Violence.csv")
data2 <- subset(Attitudes_Towards_Violence, Attitudes_Towards_Violence$Region!="All Regions" & !duplicated(Attitudes_Towards_Violence$Country))
```

```{r fig.height=15, fig.width=15}

ggplot(data2) +
  geom_bar(stat = "identity",aes(x=reorder(Country,Value), y=Value),
           fill="pink", color="black") +
  facet_wrap(~Region, ncol = 2, scales="free_y") +
  coord_flip() +
  ggtitle("% of women who agree that a husband/partner is justified in beating his wife/partner under certain circumstances")


```


```{r fig.width=10, fig.height=10}

ggplot(data2, aes(x=Value)) + 
  geom_histogram(aes(fill = Region), bins=8, color="black") +
  facet_wrap(~Region, ncol = 2) +
  ggtitle("% of women who agree that a husband/partner is justified in beating his wife/partner under certain circumstances")


```


## Prevelance of Violence

```{r, include=FALSE}
Prevelance_of_Violence<-read_csv("Prevelance_of_Violence.csv")
data3 <- subset(Prevelance_of_Violence, Prevelance_of_Violence$Region!="All Regions" & !duplicated(Prevelance_of_Violence$Country))
```


```{r fig.height=10, fig.width=10}

ggplot(data3) + 
  geom_point(stat = "identity",aes(x=reorder(Country,Value), y=Value, color=Region)) + 
  coord_flip() +
  ggtitle("Percentage of women who are victims of physical/sexual violence")

```

## Laws
```{r, include=FALSE}

Laws<-read_csv("Laws.csv")
data4 <- subset(Laws, Laws$Region!="All regions" & Laws$INC=="AIC")

```


```{r fig.height=20, fig.width=20}

ggplot(data4, aes(x = Country, y=Value, fill = Variables)) + 
  geom_col(position = "dodge") +
  facet_wrap(~Region, ncol = 2, scales = "free_y") +
  coord_flip()
```

## Female Genital Mutilation

```{r, include=FALSE}
Female_Genital_Mutilation<-read_csv("Female_Genital_Mutilation.csv")
data5 <- subset(Female_Genital_Mutilation, Female_Genital_Mutilation$Region!="All Regions" & !duplicated(Female_Genital_Mutilation$Country) & Female_Genital_Mutilation$Value>0)
```

```{r}

ggplot(data5) + 
  geom_point(stat = "identity",aes(x=reorder(Country,Value), y=Value, color=Region)) + 
  coord_flip() +
  ggtitle("Percentage of women who are victims of genital mutilation")

```


## Son Education Preference
```{r, include=FALSE}

Son_Education_Preference<-read_csv("Son_Education_Preference.csv")
data6 <- subset(Son_Education_Preference, Son_Education_Preference$Region!="All Regions" & !duplicated(Son_Education_Preference$Country))

```

```{r fig.height=10, fig.width=10}

ggplot(data6) + 
  geom_point(stat = "identity",aes(x=reorder(Country,Value), y=Value, color=Region)) + 
  coord_flip() +
  ggtitle("Percentage of people agreeing that university is more important for boys than for girls.")

```

## Access to public space
```{r, include=FALSE}
Access_To_Public_Space<-read_csv("Access_To_Public_Space.csv")
data7 <- subset(Access_To_Public_Space, Access_To_Public_Space$Region!="All Regions" & !duplicated(Access_To_Public_Space$Country))
```

```{r, fig.height=5, fig.width=9}
data7$Value_text<-recode(data7$Value, `0.0`="Equal rights", `0.5`="Customary, traditional or religious restrictions", `1.0`="No freedom of movement")

ggplot(data7, aes(x=Value_text)) + 
  geom_bar(stat = "count", aes(fill = Region),color="black") +
  ggtitle("Laws about women's freedom of movement and access to public space")
```



## Multi-variate
```{r, include=FALSE}
df1 <- data1 %>% select(Value, Country, Region)
df2 <- data2 %>% select(Value, Country, Region)
df3 <- data3 %>% select(Value, Country, Region)
df4 <- data4 %>% subset(Variables == "Laws on domestic violence") %>% select(Value, Country, Region)
df5 <- data5 %>% select(Value, Country, Region)
df6 <- data6 %>% select(Value, Country, Region)
df7 <- data7 %>% select(Value, Country, Region)

names(df1)[1] <- "Value1"
names(df2)[1] <- "Value2"
names(df3)[1] <- "Value3"
names(df4)[1] <- "Value4"
names(df5)[1] <- "Value5"
names(df6)[1] <- "Value6"
names(df7)[1] <- "Value7"


new1 <- inner_join(df1,df2,by="Country")
new2 <- inner_join(new1,df3,by="Country")
new3 <- inner_join(new2, df4, by="Country")
new4 <- inner_join(new3, df6, by="Country")
data8 <- inner_join(new4, df7, by="Country")



names(data8)[1] <- "Early Marriage"
names(data8)[4] <- "Attitude Towards Violence"
names(data8)[6] <- "Prevalence of violence"
names(data8)[8] <- "Laws on domestic violence"
names(data8)[10] <- "Son Education Preference"
names(data8)[12] <- "Access to public space"
```

```{r, fig.height=7, fig.width=15}

ggparcoord(data8, columns=c(8,4,6,10,1,12), groupColumn = "Region.x", scale = "globalminmax", title = "Parallel coordinate plot") +
  geom_line(size=2, alpha=0.5) +
  scale_color_manual(values=c(brewer.pal(8, "Set1")[c(1,8,2,4,5,3)]))


```











